name: buildanddeploy

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build
    - run: rm -rf /var/www/html/*
    - run: cp -rf /home/user/actions-runner/_work/air-ways.online/air-ways.online/dist/air-ways.online/* /var/www/html/